# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tilaus',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tilaus',
            name='maara',
        ),
        migrations.AddField(
            model_name='tilaus',
            name='koivuklapeja',
            field=models.CharField(choices=[('2', '2 heittomottia = 103,40 eur'), ('3', '3 heittomottia = 155,10 eur'), ('4', '4 heittomottia = 206,80 eur'), ('5', '5 heittomottia = 258,50 eur'), ('6', '6 heittomottia = 310,20 eur'), ('7', '7 heittomottia = 361,90 eur'), ('8', '8 heittomottia = 413,60 eur'), ('9', '9 heittomottia = 465,30 eur'), ('10', '10 heittomottia = 517,00 eur'), ('11', '11 heittomottia = 568,70 eur'), ('12', '12 heittomottia = 620,40 eur'), ('13', '13 heittomottia = 672,10 eur'), ('14', '14 heittomottia = 723,80 eur'), ('15', '15 heittomottia = 775,50 eur'), ('16', '16 heittomottia = 827,20 eur'), ('17', '17 heittomottia = 878,90 eur'), ('18', '18 heittomottia = 930,60 eur')], default='3', max_length=6),
        ),
    ]
