# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20170910_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilaus',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
