# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-13 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_tilaus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilaus',
            name='koivuklapeja',
            field=models.CharField(choices=[('2', '2 heittomottia = 114,50 eur'), ('3', '3 heittomottia = 171,75 eur'), ('4', '4 heittomottia = 229,00 eur'), ('5', '5 heittomottia = 286,25 eur'), ('6', '6 heittomottia = 343,50 eur'), ('7', '7 heittomottia = 400,75 eur'), ('8', '8 heittomottia = 458,00 eur'), ('9', '9 heittomottia = 515,25 eur'), ('10', '10 heittomottia = 572,50 eur')], default='3', max_length=6),
        ),
    ]
